# Generated by Django 5.1.15 on 2026-09-18 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('arms_cm', models.FloatField(blank=True, null=True)),
                ('thighs_cm', models.FloatField(blank=True, null=True)),
                ('hips_cm', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_weight_kg', models.FloatField()),
                ('reps', models.PositiveIntegerField(default=1)),
                ('estimated_one_rep_max', models.FloatField()),
                ('achieved_at', models.DateField()),
            ],
            options={
                'ordering': ['-estimated_one_rep_max'],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('body_fat_pct', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
