# Generated by Django 5.1.15 on 2026-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='biceps_left_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='biceps_right_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='calf_left_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='calf_right_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='calves_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='forearms_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='neck_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='shoulders_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh_left_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh_right_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
