# Generated by Django 5.1.15 on 2026-09-22 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_bodymeasurement_biceps_left_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField(blank=True, help_text='Daily step count', null=True)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Sleep duration in hours', null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, help_text='Subjective sleep quality 1-5', null=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='Subjective energy rating 1-5', null=True)),
                ('recovery_notes', models.TextField(blank=True, default='', help_text='Subjective recovery and fatigue notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_log')],
            },
        ),
    ]
