# Generated by Django 5.1.15 on 2026-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='day_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('REST', 'Rest Day'), ('SKIPPED', 'Skipped')], default='', help_text='Optional manual status: REST, SKIPPED, COMPLETED', max_length=20),
        ),
    ]
