# Generated by Django 5.1.15 on 2026-09-29 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_dailylog_day_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, default='', help_text='External URL (e.g. CDN) when not using file upload', max_length=500)),
                ('angle', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('SIDE_LEFT', 'Side — Left'), ('SIDE_RIGHT', 'Side — Right'), ('CUSTOM', 'Custom')], default='FRONT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=True, help_text='Private photos are not shared with trainers')),
                ('weight_kg', models.FloatField(blank=True, help_text='Optional weight snapshot at time of photo', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'angle'],
            },
        ),
    ]
