# Generated by Django 5.1.15 on 2026-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARY', 'Sedentary (desk job, little exercise)'), ('LIGHT', 'Light (1–3 sessions / week)'), ('MODERATE', 'Moderate (3–5 sessions / week)'), ('HIGH', 'High (6–7 sessions / week)'), ('ATHLETE', 'Athlete (twice-daily or physical job)')], default='MODERATE', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=10),
        ),
    ]
