services:
  - type: web
    name: fitlog-backend
    runtime: python
    plan: free
    region: singapore
    buildCommand: ./build.sh
    startCommand: gunicorn fitlog_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://fitlog-backend.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        sync: false   # set to your frontend URL, e.g. https://fitlog.vercel.app
      - key: DATABASE_URL
        sync: false   # paste your Neon connection string
