# Generated by Django 5.1.15 on 2026-09-18 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('WORKOUT_ASSIGNED', 'Workout Assigned'), ('WORKOUT_UPDATED', 'Workout Updated'), ('WORKOUT_COMPLETED', 'Workout Completed'), ('TRAINER_ASSIGNED', 'Trainer Assigned'), ('TRAINER_REMOVED', 'Trainer Removed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_ACCEPTED', 'Member Accepted Invitation'), ('MEMBER_SUSPENDED', 'Member Suspended'), ('FEEDBACK_POSTED', 'Trainer Feedback Posted'), ('PROGRESS_SHARED', 'Progress Shared'), ('PROGRESS_UNSHARED', 'Progress Unshared')], max_length=50)),
                ('resource_type', models.CharField(max_length=60)),
                ('resource_id', models.CharField(max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
