# Generated by Django 5.1.15 on 2026-09-29 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('CUT', 'Cut Mode'), ('BULK', 'Bulk Mode'), ('FOCUS', 'Focus Mode'), ('RECOMP', 'Recomp Mode'), ('HABIT', 'Habit Reset Mode')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('default_duration_days', models.PositiveSmallIntegerField()),
                ('default_days_per_week', models.PositiveSmallIntegerField()),
                ('pacing_kg_per_week', models.FloatField(help_text='Signed: negative = weight loss per week, positive = gain, 0 for recomp/focus/habit')),
                ('phases', models.JSONField(default=list)),
                ('workout_templates', models.JSONField(default=dict)),
                ('meal_templates', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
