# Generated by Django 5.1.15 on 2026-09-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gyminvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerclientassignment',
            name='client_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='memberships.gymmembership'),
        ),
        migrations.AddField(
            model_name='trainerclientassignment',
            name='trainer_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='memberships.gymmembership'),
        ),
        migrations.AddConstraint(
            model_name='gyminvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('gym', 'email', 'role'), name='unique_pending_invitation'),
        ),
        migrations.AddConstraint(
            model_name='gymmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER'), ('status', 'ACTIVE')), fields=('gym', 'role'), name='unique_active_gym_owner'),
        ),
        migrations.AddConstraint(
            model_name='gymmembership',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_user_gym_membership'),
        ),
        migrations.AddConstraint(
            model_name='trainerclientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('trainer_membership', 'client_membership'), name='unique_active_trainer_client'),
        ),
    ]
