# Generated by Django 5.1.15 on 2026-09-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymmembership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainerclientassignment',
            options={'ordering': ['-created_at']},
        ),
    ]
