# Generated by Django 5.1.15 on 2026-09-18 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_calories', models.PositiveIntegerField(default=2400)),
                ('protein_g', models.PositiveIntegerField(default=160)),
                ('carbs_g', models.PositiveIntegerField(default=250)),
                ('fat_g', models.PositiveIntegerField(default=70)),
                ('water_ml', models.PositiveIntegerField(default=3000)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack / Pre-Workout')], default='BREAKFAST', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(default=0.0)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('fat_g', models.FloatField(default=0.0)),
                ('time_logged', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_logged'],
            },
        ),
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('water_consumed_ml', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
