# Generated by Django 5.1.15 on 2026-09-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macrotarget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macro_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutritionday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='nutrition_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionday'),
        ),
        migrations.AddConstraint(
            model_name='nutritionday',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_nutrition_day'),
        ),
    ]
