# Generated by Django 5.1.15 on 2026-09-24 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


FIELDS = (
    'daily_calories', 'protein_g', 'carbs_g', 'fat_g', 'water_ml',
    'daily_steps', 'sleep_hours', 'weekly_workouts', 'weekly_cardio_minutes',
)


def backfill_history(apps, schema_editor):
    """Existing targets apply from the day they were created (and to earlier days by fallback)."""
    MacroTarget = apps.get_model('nutrition', 'MacroTarget')
    TargetHistory = apps.get_model('nutrition', 'TargetHistory')
    for target in MacroTarget.objects.all():
        TargetHistory.objects.get_or_create(
            user_id=target.user_id,
            effective_from=target.created_at.date(),
            defaults={f: getattr(target, f) for f in FIELDS},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_seed_diet_plan_foods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macrotarget',
            name='daily_steps',
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='macrotarget',
            name='sleep_hours',
            field=models.FloatField(default=7.5),
        ),
        migrations.AddField(
            model_name='macrotarget',
            name='weekly_cardio_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macrotarget',
            name='weekly_workouts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TargetHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_calories', models.PositiveIntegerField(default=2400)),
                ('protein_g', models.PositiveIntegerField(default=160)),
                ('carbs_g', models.PositiveIntegerField(default=250)),
                ('fat_g', models.PositiveIntegerField(default=70)),
                ('water_ml', models.PositiveIntegerField(default=3000)),
                ('daily_steps', models.PositiveIntegerField(default=8000)),
                ('sleep_hours', models.FloatField(default=7.5)),
                ('weekly_workouts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_cardio_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_from'],
                'constraints': [models.UniqueConstraint(fields=('user', 'effective_from'), name='unique_target_history_day')],
            },
        ),
        migrations.RunPython(backfill_history, migrations.RunPython.noop),
    ]
