# Generated by Django 5.1.15 on 2026-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='met_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
