# Generated by Django 5.1.15 on 2026-09-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_journey_program_cardio_and_targets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardioentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='programday',
            new_name='workouts_pr_program_07c165_idx',
            old_name='workouts_pr_program_ba0af0_idx',
        ),
    ]
