# Generated by Django 5.1.15 on 2026-09-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0003_alter_cardioentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyprogram',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='focus_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_programs', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='mode',
            field=models.CharField(choices=[('CUT', 'Cut Mode'), ('BULK', 'Bulk Mode'), ('FOCUS', 'Focus Mode'), ('RECOMP', 'Recomp Mode'), ('HABIT', 'Habit Reset Mode')], default='CUT', max_length=20),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='start_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='target_focus_1rm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='target_weekly_rate_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeyprogram',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
