# Generated by Django 5.1.15 on 2026-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_journeyprogram_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyprogram',
            name='duration_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='journeyprogram',
            name='name',
            field=models.CharField(default='Fitness Journey', max_length=150),
        ),
    ]
