# Generated by Django 5.1.15 on 2026-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_flexible_journey_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('REST', 'Rest Day')], default='UPCOMING', max_length=12),
        ),
    ]
