# Generated by Django 5.1.15 on 2026-09-28 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_created_by'),
        ('workouts', '0006_alter_programday_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDayExerciseSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_swaps', to='workouts.programday')),
                ('replacement_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swapped_into_program_days', to='exercises.exercise')),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='workouts.routineexercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('program_day', 'routine_exercise'), name='unique_program_day_exercise_swap')],
            },
        ),
    ]
