# Generated by Django 5.1.15 on 2026-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_programdayexerciseswap'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated calories burned', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Distance in km', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for cardio sets', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average heart rate bpm', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='incline_percent',
            field=models.FloatField(blank=True, help_text='Incline percentage for treadmill/cardio', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='intensity',
            field=models.CharField(blank=True, default='', help_text='Cardio intensity / zone', max_length=40),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='resistance_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Resistance level', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='speed_kmh',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
    ]
