# Generated by Django 5.1.15 on 2026-09-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workoutset_calories_workoutset_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='expected_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programday',
            name='macro_targets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programday',
            name='meal_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programday',
            name='workout_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
