# Generated by Django 5.1.15 on 2026-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_programday_expected_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='rir',
            field=models.FloatField(blank=True, help_text='Reps in Reserve — inverse complement of RPE', null=True),
        ),
    ]
