# Generated by Django 5.1.15 on 2026-10-09 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_workoutset_rir'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioentry',
            name='session',
            field=models.ForeignKey(blank=True, help_text="Set when this entry was auto-generated from a workout session's cardio sets, so it can be kept in sync on edit.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_cardio_entries', to='workouts.workoutsession'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight_kg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
