# Generated by Django 5.1.15 on 2026-09-18 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('WORKOUT_ASSIGNED', 'Workout Assigned'), ('WORKOUT_COMPLETED', 'Workout Completed'), ('FEEDBACK_POSTED', 'Trainer Feedback Posted'), ('INVITATION_RECEIVED', 'Gym Invitation Received'), ('INVITATION_ACCEPTED', 'Gym Invitation Accepted')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_on_workout_assigned', models.BooleanField(default=True)),
                ('notify_on_feedback', models.BooleanField(default=True)),
                ('notify_on_client_completion', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
